import type { TypographySystem } from '../types'

export function generateClaudePrompt(system: TypographySystem): string {
  const { scaleConfig, headingFont, bodyFont, monoFont, scaleSteps, elementMappings, spacingSteps } = system

  const lines: string[] = [
    `Implement the following typography system in this project using CSS custom properties.`,
    ``,
    `## Typography System Configuration`,
    ``,
    `**Scale method:** ${scaleConfig.method}`,
  ]

  if (scaleConfig.method === 'modular-scale') {
    lines.push(`**Base size:** ${scaleConfig.baseSize}px`)
    lines.push(`**Ratio:** ${scaleConfig.ratio}`)
  } else if (scaleConfig.method === 'utopia-fluid') {
    lines.push(`**Viewport range:** ${scaleConfig.minViewport}px – ${scaleConfig.maxViewport}px`)
    lines.push(`**Base size:** ${scaleConfig.minBaseSize}px (min) / ${scaleConfig.maxBaseSize}px (max)`)
    lines.push(`**Ratio:** ${scaleConfig.minRatio} (min) / ${scaleConfig.maxRatio} (max)`)
  }

  lines.push(``)
  lines.push(`## Fonts`)
  lines.push(`- **Headings:** ${headingFont.family} (weights: ${headingFont.weights.join(', ')})`)
  lines.push(`- **Body:** ${bodyFont.family} (weights: ${bodyFont.weights.join(', ')})`)
  if (monoFont) {
    lines.push(`- **Mono:** ${monoFont.family} (weights: ${monoFont.weights.join(', ')})`)
  }
  lines.push(`- Load from Google Fonts`)

  lines.push(``)
  lines.push(`## Type Scale`)
  lines.push(`| Step | Size (rem) | Size (px) | Line Height |`)
  lines.push(`|------|-----------|-----------|-------------|`)
  for (const step of scaleSteps) {
    const clampNote = step.clamp ? ` (fluid: ${step.clamp})` : ''
    lines.push(`| ${step.name} | ${step.sizeRem}rem | ${step.sizePx}px | ${step.lineHeight}${clampNote} |`)
  }

  if (elementMappings.length > 0) {
    lines.push(``)
    lines.push(`## Element Mapping`)
    lines.push(`| Element | Scale Step | Weight | Line Height | Letter Spacing |`)
    lines.push(`|---------|-----------|--------|-------------|---------------|`)
    for (const m of elementMappings) {
      lines.push(`| ${m.element} | step-${m.scaleStep} | ${m.fontWeight} | ${m.lineHeight} | ${m.letterSpacing ?? 'normal'} |`)
    }
  }

  if (spacingSteps.length > 0) {
    lines.push(``)
    lines.push(`## Spacing Scale`)
    for (const s of spacingSteps) {
      const value = s.clamp ?? `${s.sizeRem}rem`
      lines.push(`- ${s.name}: ${value} (${s.sizePx}px)`)
    }
  }

  lines.push(``)
  lines.push(`## Instructions`)
  lines.push(`1. Add Google Fonts link/import for the fonts listed above`)
  lines.push(`2. Create CSS custom properties in :root for the type scale, line heights, and spacing`)
  lines.push(`3. Apply element styles (h1-h6, body, etc.) using the mappings above`)
  lines.push(`4. Use the spacing scale for margins and padding`)
  lines.push(``)
  lines.push(`Generated by TypeForge (type.ethanede.com)`)

  return lines.join('\n')
}

export function generateGenericAiPrompt(system: TypographySystem): string {
  return generateClaudePrompt(system)
    .replace(/^Implement/, 'Please implement')
    .replace('Generated by TypeForge (type.ethanede.com)', 'Generated by TypeForge')
}

export function generateSystemPromptSnippet(system: TypographySystem): string {
  const { headingFont, bodyFont, scaleConfig, scaleSteps } = system
  const lines = [
    `## Typography`,
    `Headings: ${headingFont.family} | Body: ${bodyFont.family}`,
    `Scale: ${scaleConfig.method}, base ${scaleConfig.method === 'modular-scale' ? `${scaleConfig.baseSize}px @ ${scaleConfig.ratio}` : 'fluid'}`,
    `Steps: ${scaleSteps.map(s => `${s.name}=${s.sizeRem}rem`).join(', ')}`,
  ]
  return lines.join('\n')
}
